getwd()
setwd("C:/Users/DANIPZA/Desktop/pylinR/Rclass")
dir.create("corian")
dir()
help("log")
log(8,base = 2)
vec1 <- 1:5
vec2 <- c(1,4,5,5.7)
vec3 <- c(vec1,vec2)
help("rnorm")
vect4 <- rnorm(5,mean = 5,sd = 2)
vect5 <- sum(vect4)
vect5 <- vect5/5
help("runif")
vec6 <- runif(5,min = 4,max = 7)
help("rchisq")
help("seq")